<a href="https://colab.research.google.com/github/AJAbeSMU/FlowShop2/blob/main/testing_Codes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
J = 1
for m3 in permutations(range(J),J):
  print(m3)

(0,)


In [ ]:
# A Python program to print all
# permutations using library function
from itertools import permutations
 
# Get all permutations of [1, 2, 3, 4]
perm = permutations([1, 2, 3, 4,])
 
# Print the obtained permutations
for i in list(perm):
    print (i)
    

(1, 2, 3, 4)
(1, 2, 4, 3)
(1, 3, 2, 4)
(1, 3, 4, 2)
(1, 4, 2, 3)
(1, 4, 3, 2)
(2, 1, 3, 4)
(2, 1, 4, 3)
(2, 3, 1, 4)
(2, 3, 4, 1)
(2, 4, 1, 3)
(2, 4, 3, 1)
(3, 1, 2, 4)
(3, 1, 4, 2)
(3, 2, 1, 4)
(3, 2, 4, 1)
(3, 4, 1, 2)
(3, 4, 2, 1)
(4, 1, 2, 3)
(4, 1, 3, 2)
(4, 2, 1, 3)
(4, 2, 3, 1)
(4, 3, 1, 2)
(4, 3, 2, 1)


In [ ]:
import numpy as np
m = np.matrix([[7, 6, 5, 8], [5, 12, 4, 3], [2, 4, 5, 3]])
print('Matrix is:\n', m)

Matrix is:
 [[ 7  6  5  8]
 [ 5 12  4  3]
 [ 2  4  5  3]]


In [ ]:
# importing numpy as np
import numpy as np
  
  
# creating first matrix
A = np.array([7, 6, 5, 8])
  
# creating second matrix
B = np.array([5, 12, 4, 3])

# creating third matrix
C = np.array([2, 4, 5, 3])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Printing elements of third matrix")
print(C)
  
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))
print("Addition of two matrix")
print(np.add(B, C))

Printing elements of first matrix
[7 6 5 8]
Printing elements of second matrix
[ 5 12  4  3]
Printing elements of third matrix
[2 4 5 3]
Addition of two matrix
[12 18  9 11]
Addition of two matrix
[ 7 16  9  6]


In [ ]:
# using min() + key
# Row with Minimum element in Matrix 
res = min(np.add(A, B),np.add(B, C), key = min)
  
# printing result
print ("Minimum element sublist is : " + str(res))

Minimum element sublist is : [ 7 16  9  6]


In [ ]:
# import pandas module
import pandas as pd
 
# create a dataframe1
# with 2 rows and 4 columns
data1 = pd.DataFrame({
    'Xi': [12, 18, 9, 11],
    'Yi': [7, 16, 9, 6]
})
# display dataframe
print(data1)
 
# get the minimum in Yi  column
print(data1['Yi'].min())



   Xi  Yi
0  12   7
1  18  16
2   9   9
3  11   6
6


In [ ]:
# create a dataframe
# with 2 rows and 3 columns
data2 = pd.DataFrame({
    'Xi': [12, 18, 9],
    'Yi': [7, 16, 9]
})
# display dataframe
print(data2)
 
# get the minimum in Xi  column
print(data2['Xi'].min())

   Xi  Yi
0  12   7
1  18  16
2   9   9
9


In [ ]:
# create a dataframe
# with 2 rows and 3 columns
data3 = pd.DataFrame({
    'Xi': [12, 18],
    'Yi': [7, 16]
})
# display dataframe
print(data3)
 
# get the minimum in Yi  column
print(data3['Yi'].min())

   Xi  Yi
0  12   7
1  18  16
7


In [ ]:
# create a dataframe
# with 2 rows and 1 columns
data = pd.DataFrame({
    'Xi': [12],
    'Yi': [7]
})
# display dataframe
print(data)
 
# get the minimum in Yi  column
print(data['Xi'].min())

   Xi  Yi
0  12   7
12


In [ ]:
# Jobs in Optimal Sequence

# Xi to Yi
#  2 1 0 3
# Job 3, Job 2, Job 1, Job 4

